### ISSUE TITLE
Feature request: run tests as arbitrary bash scripts

### ISSUE THREAD

**Issue by thompsnm** [sequenceiq/docker-e2e-protractor#3]
Hi,

I came across this project because it has the highest downloads of all Protractor images on Docker Hub. I really appreciate what you've done, but it doesn't quite suit my needs. I want to test a locally running instance of my Angular application, so I need to coordinate the process of building / serving my code and actually running the tests so that Protractor doesn't start before the application is available. The easiest way I found to synchronize the two was to write a simple Node.js script that executed my Protractor tests in as a callback once Webpack was done building. To get that running in a Docker container, I actually forked this repo and [modified it slightly to allow `run-e2e-tests.sh` to run arbitrary bash scripts](https://github.com/sequenceiq/docker-e2e-protractor/compare/master...thompsnm:master#diff-c3969cfd64138b19934585c12f1dbb45L28). In the end, my `docker run` command looked something like this:

    docker run -it --rm --name protractor-runner -v $(PWD):/protractor/project thompsnm/docker-e2e-protractor npm run e2e

I'm curious, would you be open to updating this image to allow for running arbitrary bash scripts? I could open a pull request from my fork if you like that flow. Alternatively, I could look into ways to improve `run-e2e-tests.sh` so that it uses `protractor` if just a config file is passed in, but will execute the entire script if something more complicated is passed. The latter would keep the image backward-compatible.

Just let me know!

**Comment by aszegedi** [comment]
Hi! So sorry for my late response!

I hope these changes are met your needs:

1. https://github.com/sequenceiq/docker-e2e-protractor/releases/tag/2.0
2. https://hub.docker.com/r/hortonworks/docker-e2e-protractor/builds/bbmqkjc2pyz7sjklbackug4/
